#####
# Generation
# Uses the default/official MySQl 8.0 image with some little tricks
# on the configuration to work with Laravel/Lumen
#####
FROM mysql:8.0

MAINTAINER Jose Vieira <hello@josevieira.me>

COPY mode.cnf /etc/mysql/mysql.conf.d/mode.cnf
